apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: git-pipeline
  namespace: ace
spec:
  workspaces:
  - name: shared-workspace
    # description: The git repo will be cloned into this workspace and the readme will be read from it.
  tasks:
    - name: fetch-repository
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
      - name: output
        workspace: shared-workspace