apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: git-pipelinerun
spec:
  pipelineRef:
    name: git-pipeline
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: workspace-pvc