apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: ace-cicd-triggertemplate
spec:
  params:
  - name: git-repo-url
    description: The git repository url
  - name: git-revision
    description: The git revision
    default: master
  - name: git-repo-name
    description: The name of the deployment to be created / patched
  - name: pathToDockerFile
    description: Path to the docker file
    # default: /workspace/git-source/products/cicd/DOCKERFILE
  - name: pathToContext
    description: Context path
    # default: /workspace/git-source/products/cicd
  - name: bar_file_name
    description: default bar file name
    # default: bar_file_name=simpleGET.bar
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: git-source
      namespace: ace
    spec:
      type: git
      params:
      - name: revision
        value: $(params.git-revision)
      - name: url
        value: $(params.git-repo-url)
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: docker-image
      namespace: ace
    spec:
      type: image
      params:
      - name: url
        # value: image-registry.openshift-image-registry.svc:5000/ace/$(params.git-repo-name):latest
        value: default-route-openshift-image-registry.kbcl2-450523-ec111ed5d7db435e1c5eeeb4400d693f-0000.eu-gb.containers.appdomain.cloud/ace/test5:latest
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      name: cicd-$(params.git-repo-name)-git-repo-$(uid)
      namespace: ace
    spec:
      pipelineRef:
        name: ace-pipeline
      serviceAccountName: cicd-ace-sa
      resources:
      - name: git-source
        resourceRef:
          name: git-source
      - name: docker-image
        resourceRef:
          name: docker-image
      params:
      - name: pathToDockerFile
        value: /workspace/git-source/products/cicd/DOCKERFILE
      - name: pathToContext
        value: /workspace/git-source/products/cicd #configure: may change according to your source
      - name: bar_file_name
        value: bar_file_name=simpleGET.bar #this filename should be in the format "bar_file_name=<actual_bar_file_name_with_extension>"

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: ace-cicd-triggerbinding
  namespace: ace
spec:
  params:
  - name: git-repo-url
    value: https://github.com/Kinshuk1993/cp4i-deployment-samples
  - name: git-repo-name
    value: cp4i-deployment-samples
  - name: git-revision
    value: tkn
  - name: pathToDockerFile
    value: /workspace/git-source/products/cicd/DOCKERFILE
  - name: pathToContext
    value: /workspace/git-source/products/cicd
  - name: bar_file_name
    value: bar_file_name=simpleGET.bar

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: ace-cicd-trigger
spec:
  serviceAccountName: cicd-ace-sa
  triggers:
  - bindings:
    - name: ace-cicd-triggerbinding
    template:
      name: ace-cicd-triggertemplate

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-triggers-role
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups:
  - triggers.tekton.dev
  resources:
  - eventlisteners
  - triggerbindings
  - triggertemplates
  - pipelineresources
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - pipelineresources
  - secrets
  verbs:
  - create
  - get
  - list
  - watch

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-ace-sa
secrets:
  - name: cicd-ace


---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-rolebinding
subjects:
- kind: ServiceAccount
  name: cicd-ace-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-triggers-role

---

apiVersion: v1
kind: Secret
metadata:
  name: webhook-secret
stringData:
  #https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line#creating-a-token
  token: c1b1bb81e354047048c8b1da71e9c9fd6229972d
  secret: cicd-secret-webhook