apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  creationTimestamp: '2020-05-05T11:08:40Z'
  generation: 19
  name: docker-build-and-deploy
  namespace: ace
  resourceVersion: '17050933'
  selfLink: /apis/tekton.dev/v1alpha1/namespaces/ace/pipelines/docker-build-and-deploy
  uid: e46e6101-5814-49ae-bed6-f9a74adbd3e8
spec:
  params:
    - default: acetek
      name: IMAGE_NAME
      type: string
    - default: accept
      name: LICENSE
      type: string
    - default: acetek
      name: APP_NAME
      type: string
    - default: '7800'
      name: PORT
      type: string
  tasks:
    - name: build
      params:
        - name: ARGS
          value:
            - start-build
            - ace-app-bc
            - '--wait'
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: deploy
      params:
        - name: ARGS
          value:
            - new-app
            - '--image-stream'
            - $(params.IMAGE_NAME)
            - '--env'
            - LICENSE=$(params.LICENSE)
            - '--name'
            - $(params.APP_NAME)
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: expose
      params:
        - name: ARGS
          value:
            - expose
            - svc/$(params.APP_NAME)
            - '--port'
            - $(params.PORT)
      runAfter:
        - deploy
      taskRef:
        kind: ClusterTask
        name: openshift-client