apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: ace-cicd-triggertemplate
spec:
  params:
  - name: git-repo-url
    description: The git repository url
  - name: git-revision
    description: The git revision
    default: master
  - name: git-repo-name
    description: The name of the deployment to be created / patched
  - name: SCRIPT
    description: oc script to run
  resourcetemplates:

  # this resource is created to do a git clone to get files to apply using build pipelinerun
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: git-source
      namespace: ace
    spec:
      type: git
      params:
      - name: revision
        value: $(params.git-revision)
      - name: url
        value: $(params.git-repo-url)

  # runs commands against the cluster where the task run is being executed
  # https://github.com/tektoncd/catalog/tree/v1beta1/openshift-client
  - apiVersion: tekton.dev/v1beta1
    kind: Task
    metadata:
      name: openshift-client
    spec:
      params:
      - name: SCRIPT
        description: The OpenShift CLI arguments to run
        type: string
        default: "oc $@"
      resources:
        inputs:
          - name: git-source
            type: git
            optional: true
      steps:
        - name: oc
          image: quay.io/openshift/origin-cli:latest
          script: "$(params.SCRIPT)"

  # pipeline to call task
  - apiVersion: tekton.dev/v1alpha1
    kind: Pipeline
    metadata:
      name: cicd-$(params.git-repo-name)-pipeline1-$(uid)
      namespace: ace
    spec:
      params:
        - name: SCRIPT
          description: The OpenShift CLI arguments to run
          type: string
          default: "oc $@"
      resources:
        - name: git-source
          type: git
      tasks:
        - name: cicd-openshift-client-$(uid)
          taskRef:
            name: openshift-client
          params:
            - name: SCRIPT
              value: "oc apply -f /workspace/git-source/products/cicd/pipeline-objects/pipeline.yaml"
          resources:
            inputs:
              - name: git-source
                resource: git-source

  # pipelinerun
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      name: cicd-$(params.git-repo-name)-pipelinerun1-$(uid)
      namespace: ace
    spec:
      pipelineRef:
        name: cicd-$(params.git-repo-name)-pipeline1-$(uid)
      serviceAccountName: cicd-ace-sa
      resources:
      - name: git-source
        resourceRef:
          name: git-source

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: ace-cicd-triggerbinding
  namespace: ace
spec:
  params:
  - name: git-repo-url
    value: https://github.com/Kinshuk1993/cp4i-deployment-samples
  - name: git-repo-name
    value: cp4i-deployment-samples
  - name: git-revision
    value: tkn

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: ace-cicd-trigger
spec:
  serviceAccountName: cicd-ace-sa
  triggers:
  - bindings:
    - name: ace-cicd-triggerbinding
    template:
      name: ace-cicd-triggertemplate

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-triggers-role
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups:
  - triggers.tekton.dev
  resources:
  - eventlisteners
  - triggerbindings
  - triggertemplates
  - pipelineresources
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - tekton.dev
  resources:
  - pipelines
  - tasks
  - pipelineruns
  - pipelineresources
  - secrets
  verbs:
  - create
  - get
  - list
  - watch

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-ace-sa
secrets:
  - name: cicd-ace

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-rolebinding
subjects:
- kind: ServiceAccount
  name: cicd-ace-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-triggers-role
