apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
    - name: revision
      value: tkn
    - name: url
      value: https://github.com/IBM/cp4i-deployment-samples
